module VerifyExamples.PixelEngine.Image.MultipleImages0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PixelEngine.Image exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#multipleImages: \n\n    multipleImages [((4,2),fromSrc \"img.png\" |> movable \"id\")]\n    --> multipleImages [((4,2),fromSrc \"img.png\")]" <|
        \() ->
            Expect.equal
                (
                multipleImages [((4,2),fromSrc "img.png" |> movable "id")]
                )
                (
                multipleImages [((4,2),fromSrc "img.png")]
                )