module VerifyExamples.Grid.EmptyPositions0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid Int
grid =
    fill
        (always <| Just <| 42)
        dimensions
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "#emptyPositions: \n\n    grid |> remove (2,2) |> emptyPositions\n    --> [(2,2)]" <|
        \() ->
            Expect.equal
                (
                grid |> remove (2,2) |> emptyPositions
                )
                (
                [(2,2)]
                )