module VerifyExamples.Grid.Filter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid Int
grid =
    empty dimensions
        |> insert (2,4) 2
        |> insert (2,3) 42
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "#filter: \n\n    grid |> filter (\\_ -> (==) 42) |> values\n    --> [42]" <|
        \() ->
            Expect.equal
                (
                grid |> filter (\_ -> (==) 42) |> values
                )
                (
                [42]
                )