module VerifyExamples.Grid.FromList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid Int
grid =
    empty dimensions
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "#fromList: \n\n    [((2,2),42),((2,1),20)] |> fromList dimensions\n    --> grid |> insert (2,2) 42 |> insert (2,1) 20" <|
        \() ->
            Expect.equal
                (
                [((2,2),42),((2,1),20)] |> fromList dimensions
                )
                (
                grid |> insert (2,2) 42 |> insert (2,1) 20
                )