module VerifyExamples.Grid.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid a
grid =
    empty dimensions
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    grid |> get ( -1, 0 )\n    --> grid |> get ( (dimensions |> .columns) - 1, 0 )" <|
        \() ->
            Expect.equal
                (
                grid |> get ( -1, 0 )
                )
                (
                grid |> get ( (dimensions |> .columns) - 1, 0 )
                )