module VerifyExamples.Grid.Update0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid a
grid =
    empty dimensions
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "#update: \n\n    grid |> update (2,2) (always <| Just 42)\n    --> grid |> insert (2,2) 42" <|
        \() ->
            Expect.equal
                (
                grid |> update (2,2) (always <| Just 42)
                )
                (
                grid |> insert (2,2) 42
                )