module VerifyExamples.PixelEngine.Tile.MultipleTiles1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PixelEngine.Tile exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#multipleTiles: \n\n    multipleTiles [fromPosition (0,0) |> movable \"id\"]\n    --> fromPosition (0,0)" <|
        \() ->
            Expect.equal
                (
                multipleTiles [fromPosition (0,0) |> movable "id"]
                )
                (
                fromPosition (0,0)
                )