module VerifyExamples.PixelEngine.Tile.MultipleTiles0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PixelEngine.Tile exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#multipleTiles: \n\n    multipleTiles [fromPosition (0,0) ] |> movable \"id\"\n    --> fromPosition (0,0) |> movable \"id\"" <|
        \() ->
            Expect.equal
                (
                multipleTiles [fromPosition (0,0) ] |> movable "id"
                )
                (
                fromPosition (0,0) |> movable "id"
                )