module VerifyExamples.Grid.Bordered.IsValid2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid.Bordered exposing (..)



grid : Grid a
grid =
    empty
        { columns=42
        , rows=3
        }



spec2 : Test.Test
spec2 =
    Test.test "#isValid: \n\n    grid |> isValid (-1,0)\n    --> False" <|
        \() ->
            Expect.equal
                (
                grid |> isValid (-1,0)
                )
                (
                False
                )